### ISSUE TITLE
Geekttrss should show feed hierarchy in "manage feeds" menu

### ISSUE THREAD

**Issue by hobgoblinsmaster** [fbarthelery/geekttrss#18]
I have many feeds in my ttrss and they are organized hierarchically by work/home interest, subject, language etc. I'd love that I can recover this organization in "manage feed" menu at least and maybe in the feed list also.

Thanks.

**Comment by fbarthelery** [comment]
The UX for a full hierarchy tree in the feed list is not very good (a full tree in the nav drawer). I actually removed the early implementation that I have of it because it was too complex both in code and usage.

In the Manage feeds module, we have more screen space available so this would be more suitable. There is definitely room for improvements in this area.

**Comment by hobgoblinsmaster** [comment]
You are right that a full tree in the nav drawer can be hard to code a have a bad ui, for this part I thought more to something like this:
_____
### 📁 folder
#### 📁 subfolder
##### 🦅 feed 1
##### 🦆 feed 2
#### 📁 subfolder 2
##### 🦉feed 3
_____
Completely static without folding capability but a visual representation off the hierarchy and sorting.

Anyway, I really like Geekttrss, it is a beautiful way to read my feeds from my mobile. Thanks

**Comment by fbarthelery** [comment]
Fixed in [1.6.7](https://github.com/fbarthelery/geekttrss/releases/tag/1.6.7)
